import pandas as pd
import oracledb
import os
from sqlalchemy import create_engine

# Database connection parameters
DB_USER = "bank_user"
DB_PASSWORD = "your_password"  # Replace with your Oracle XE password
DB_DSN = "localhost:1521/XEPDB1"  # Default DSN for Oracle XE

# SQL to create tables
CREATE_BANKS_TABLE = """
CREATE TABLE Banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL UNIQUE
)
"""

CREATE_REVIEWS_TABLE = """
CREATE TABLE Reviews (
    review_id NUMBER PRIMARY KEY,
    bank_id NUMBER NOT NULL,
    review_text VARCHAR2(4000),
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    review_date DATE,
    source VARCHAR2(50),
    sentiment_label VARCHAR2(20),
    sentiment_score NUMBER,
    themes VARCHAR2(500),
    FOREIGN KEY (bank_id) REFERENCES Banks(bank_id)
)
"""

def setup_database(connection):
    """Create tables in the Oracle database."""
    try:
        cursor = connection.cursor()
        # Drop tables if they exist (for clean setup)
        cursor.execute("DROP TABLE Reviews PURGE")
        cursor.execute("DROP TABLE Banks PURGE")
    except oracledb.DatabaseError:
        pass  # Ignore if tables don't exist

    # Create tables
    cursor.execute(CREATE_BANKS_TABLE)
    cursor.execute(CREATE_REVIEWS_TABLE)
    connection.commit()
    print("Tables created successfully.")

def insert_data(connection, reviews_df):
    """Insert data into Banks and Reviews tables."""
    cursor = connection.cursor()

    # Insert unique banks
    banks = reviews_df['bank'].unique()
    bank_id_map = {}
    for bank_name in banks:
        cursor.execute(
            "INSERT INTO Banks (bank_name) VALUES (:1) RETURNING bank_id INTO :2",
            [bank_name, None]
        )
        bank_id = cursor.fetchone()[0]
        bank_id_map[bank_name] = bank_id
    connection.commit()

    # Insert reviews
    for _, row in reviews_df.iterrows():
        themes_str = ','.join(row['themes']) if isinstance(row['themes'], list) else row['themes']
        cursor.execute(
            """
            INSERT INTO Reviews (review_id, bank_id, review_text, rating, review_date, source, sentiment_label, sentiment_score, themes)
            VALUES (:1, :2, :3, :4, TO_DATE(:5, 'YYYY-MM-DD'), :6, :7, :8, :9)
            """,
            [
                row['review_id'],
                bank_id_map[row['bank']],
                row['review'],
                row['rating'],
                row['date'],
                row['source'],
                row['sentiment_label'],
                row['sentiment_score'],
                themes_str
            ]
        )
    connection.commit()
    print(f"Inserted {len(reviews_df)} reviews into the database.")

def main():
    # Load analyzed reviews from Task 2
    input_path = 'data/analyzed_reviews.csv'
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"{input_path} not found. Run Task 2 first.")
    
    df = pd.read_csv(input_path)
    
    # Connect to Oracle database
    try:
        connection = oracledb.connect(user=DB_USER, password=DB_PASSWORD, dsn=DB_DSN)
        print("Connected to Oracle database.")
    except oracledb.DatabaseError as e:
        print(f"Database connection error: {e}")
        return

    # Setup tables
    setup_database(connection)

    # Insert data
    insert_data(connection, df)

    # Generate SQL dump
    cursor = connection.cursor()
    with open('data/bank_reviews_dump.sql', 'w') as f:
        f.write("-- SQL Dump for bank_reviews database\n\n")
        f.write(CREATE_BANKS_TABLE + ";\n\n")
        f.write(CREATE_REVIEWS_TABLE + ";\n\n")
        
        # Export Banks data
        cursor.execute("SELECT bank_id, bank_name FROM Banks")
        f.write("INSERT INTO Banks (bank_id, bank_name) VALUES\n")
        banks = cursor.fetchall()
        for i, (bank_id, bank_name) in enumerate(banks):
            f.write(f"({bank_id}, '{bank_name}'){'' if i == len(banks)-1 else ','}\n")
        f.write(";\n\n")

        # Export Reviews data
        cursor.execute("SELECT review_id, bank_id, review_text, rating, TO_CHAR(review_date, 'YYYY-MM-DD'), source, sentiment_label, sentiment_score, themes FROM Reviews")
        f.write("INSERT INTO Reviews (review_id, bank_id, review_text, rating, review_date, source, sentiment_label, sentiment_score, themes) VALUES\n")
        reviews = cursor.fetchall()
        for i, row in enumerate(reviews):
            review_text = row[2].replace("'", "''") if row[2] else ''
            themes = row[8].replace("'", "''") if row[8] else ''
            f.write(f"({row[0]}, {row[1]}, '{review_text}', {row[2]}, TO_DATE('{row[4]}', 'YYYY-MM-DD'), '{row[5]}', '{row[6]}', {row[7]}, '{themes}'){'' if i == len(reviews)-1 else ','}\n")
        f.write(";\n")
    
    connection.close()
    print("SQL dump saved to data/bank_reviews_dump.sql")

if __name__ == "__main__":
    main()